InranetSystem/InranetSystem/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaDatos;
using CapaEntidad;
using CapaNegocio;

namespace InranetSystem.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        ClienteMANAGER managerCliente = new ClienteMANAGER();
        public ActionResult IndexCliente()
        {
            IEnumerable<Cliente> objeto = null;
            objeto = managerCliente.listarCliente();
            
            return View(objeto);
        }
        public JsonResult ListAjax()
        {
            IEnumerable<Cliente> objeto = null;

            objeto = managerCliente.listarCliente();

            return Json(objeto);
        }
        public JsonResult CreateCliente(string nombre, string apepat, string apemat, string telef, string dni)
        {

            try
            {
                managerCliente.RegistrarCliente(nombre, apepat, apemat, telef, dni);
                string msg = "Exito se guardo controller";
                return Json(new { msg });

            }
            catch (Exception e)
            {
                string msg = "Error";
                return Json(new { msg });
            }

        }
        [HttpPost]
        public JsonResult BusquedaXDNI(int dni)
        {
            Cliente cliente = new Cliente();
            try
            {
                cliente = managerCliente.BuqquedaXDni(dni);
                return Json(new { cliente });
            }catch(Exception e)
            {
                string msg = "error";
                return Json(new { msg });
            }
        }

    }
}

InranetSystem/InranetSystem/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaDatos;
using CapaEntidad;
using CapaNegocio;

namespace InranetSystem.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta
        VentaMANAGER managerVenta = new VentaMANAGER();
        TipoProductoMANAGER managerTipoProducto = new TipoProductoMANAGER();
        ProductoMANAGER managerProducto = new ProductoMANAGER();
        public ActionResult IndexVenta()
        {
            IEnumerable<Venta> objeto = null;
            objeto = managerVenta.listarVenta();
            ViewBag.TipoProducto = new SelectList(managerTipoProducto.listarTipoProducto(), "idTipo", "Nombre");
            ViewBag.Producto = new SelectList(managerProducto.listarProducto(), "idProducto", "Nombre");

            return View(objeto);
        }
        public JsonResult ComboProducto(int id)
        {

            IEnumerable<Producto> objeto = null;

            try
            {
                objeto = managerProducto.ComboProducto(id);
                string msg = "Se obtuvo el registro";
                return Json(new { msg, objeto });
            }
            catch (Exception e)
            {
                string msg = "Error";
                return Json(new { msg });
            }

        }
    }
}

InranetSystem/InranetSystem/Views/Venta/IndexVenta.cshtml
@model IEnumerable<CapaEntidad.Venta>

@{
    Layout = "~/Views/Plantilla/View1.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.intellisense.js"></script>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {

        $('[data-toggle="m-tooltip"]').tooltip();

        var fnHC_AjaxSearchPersona_DNI;

        var prmNot = {
            type: 'danger',
            timer: 1000,
            z_index: 2000,
            animate: {
                enter: 'animated bounce',
                exit: 'animated bounce'
            },
            placement: {
                from: 'top',
                align: 'center'
            }
        };

        var prmNot2 = {
            type: 'alert alert-warning',
            timer: 1000,
            z_index: 2000,
            animate: {
                enter: 'animated bounce',
                exit: 'animated bounce'
            },
            placement: {
                from: 'top',
                align: 'center'
            }
        };
        var prmNot3 = {
            type: 'alert alert-success alert-dismissible fade show',
            timer: 1000,

            z_index: 2000,
            animate: {
                enter: 'animated bounce',
                exit: 'animated bounce'
            },
            placement: {
                from: 'top',
                align: 'center'
            }
        };

        $("#btnNuevo").click(function () {
            $('#formCreatePerson').trigger("reset");

            $("#datasearch").val('');
            $("#nomco").val('');
            $("#ruc").val('');
            $("#raz").val('');
            $("#dire").val('');
            $("#nompriE").val('');
            $("#movilcre").val('');
            $("#emailcre").val('');
            $("#perscre").val('');
            $("#myModalCreate").modal({ backdrop: "static" }, { keyboard: false });
        });

        $("#myModalCreate").on("click", "#btnSendCreate", function () {

            //nombre, apepat, apemat, telef, dni
            let nombre = $("#nomcre").val();
            let apepat = $("#apatcre").val();
            let apemat = $("#apmatcre").val();
            let telef = $("#telcre").val();
            let dni = $("#dnicre").val();


            let datasend = {
                nombre: nombre,
                apepat: apepat,
                apemat: apemat,
                telef: telef,
                dni: dni


            };


            $.ajax({
                url:'@Url.Action("CreateCliente", "Cliente")',
                type: "POST",
                data: JSON.stringify(datasend),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (result) {
                    console.log(JSON.stringify(result) + typeof result);
                    if (result) {
                        $("#myModalCreate").modal("hide");
                        updateTableAjax();
                        var content = {};
                        content.message = 'El Cliente se registro correctamente ';
                        content.icon = 'icon la la-check';
                        fnHC_AjaxSearchPersona_DNI(dni);
                        $.notify(content, prmNot3)

                        setTimeout(function () {

                        }, 1000);
                    } else {
                        console.log('Ocurrio un error');
                    }

                },
                error: function (err) {
                    alert(err.statusText);
                }
               });
        });

        (typeheadHC = function () {
            var substringMatcher = function (strs) {
                return function findMatches(q, cb) {
                    var matches, substringRegex;


                    matches = [];


                    var substrRegex = new RegExp(q, 'i');

                    $.each(strs, function (i, str) {
                        if (substrRegex.test(str)) {
                            matches.push(str);
                        }
                    });

                    cb(matches);
                };
            };

            //Asigno el atributo al campo ya que la funcion le quita el focus
            $('#datasearch').focus();
        })();
        //BUSCAR CLIENTES POR DNI

         fnHC_AjaxSearchPersona_DNI = (dni) => {

                let datasend = { dni: dni };

                $.ajax({
                    url: '@Url.Action("BusquedaXDNI", "Cliente")',
                    data: JSON.stringify(datasend),
                    type: 'POST',
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {

                        console.log(JSON.stringify(result));

                        if ($.isEmptyObject(result.Cliente)) {
                            $("#lbl_help_search").text("No se obtuvo resultados de la busqueda de Pacientes sin Historia Clinica");
                            console.log('No se obtuvo resultados');
                            $("#dvnomape").empty();
                            $("#dvima").empty();
                            $("#dvdni").empty();
                            $("#dvid").empty();

                            swal({
                                title: 'Persona no Registrada',
                                text: "¿Desea crear nuevo Cliente?",
                                type: 'warning',
                                showCancelButton: true,
                                confirmButtonText: 'Si, Crear!'

                            }).then(function (result) {

                                if (result.value) {

                                    let dni = $("#datasearch").val().trim();
                                    $("#dnicre").val(dni);
                                    //datareniec();
                                    $("#myModalCreate").modal("hide");
                                    $("#ModalCreate").modal({ backdrop: "static" }, { keyboard: false });
                                }
                            });
                        } else {
                            console.table(result);
                            let data = result.Cliente;
                            let i;

                            $("#lbl_help_search").text("Resultados de la Busqueda de Pacientes sin Historia Clinica");

                            $('#nompriE').val(data.apellidos);

                            $('#dvid').val(result.persona.idCliente);

                        }
                    },
                    error: function (error) {
                        alert('Error!' + JSON.stringify(error));
                    }
                });

        };

        $("#fn").click(function () {
            $('#datasearch').typeahead('destroy');

        });
        function updateTableAjax() {
           $.ajax({
                url:'@Url.Action("ListAjax", "Cliente")',
                type: "POST",
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (result) {
                    console.log(JSON.stringify(result));
                    let s = result;
                    console.log(s.length);
                    let i;
                    $(".m-datatable__body").empty();

                    for (i = 0; i <= s.length; i++) {
                        $(".m-datatable__body").append("<tr data-row='5' class='m-datatable__row m-datatable__row--even'>"
                            + `<td data-field='Id' class="m-datatable__cell m-datatable__cell--sort"><span style='width: 110px;'>${result[i].idCliente}</span></td>`
                            + `<td data-field='Nombre Alergia' class="m-datatable__cell m-datatable__cell--sort"><span style='width: 110px;'>${result[i].nombres}</span></td>`
                            + `<td data-field='Apellidos  class="m-datatable__cell m-datatable__cell--sort"><span style='width: 110px;'>${result[i].nomCom}</span></td>`
                            + `<td data-field='Telefono' class="m-datatable__cell m-datatable__cell--sort"><span style='width: 110px;'>${result[i].telefono}</td>`
                            + `<td data-field='DNI' class="m-datatable__cell m-datatable__cell--sort"><span style='width: 110px;'>${result[i].dni}</td>`
                            + "<td data-field='ACCIONES'  class='m-datatable__cell--center'><span style='width: 110px;'><button id='btnConsultar' class='m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill'><i class='flaticon-search-magnifier-interface-symbol'></i></button><button id='btnEditar' class='m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill'><i class='la la-edit'></i></button><button id='btnEliminar' class='m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill'><i class='la la-trash'></i></button></span></td></tr>");


                    };
                },
                error: function (err) {
                    console.log(err.statusText);
                }

            });
        }

    });

</script>


<a href="#" id="btnNuevo" class="btn btn-success"><i class="fa fa-plus"></i></a>
<table class="m-datatable" id="html_table" width="100%">
    <tr>
        <th>
            #
        </th>
        <th>
            Datos Cliente
        </th>
        <th>
            Total
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idVenta)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.nombapells)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>


            <td>
                <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit details" id="btnEditar">
                    <i class="la la-edit"></i>
                </a>
                <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete" id="btnEliminar">
                    <i class="la la-trash"></i>
                </a>
            </td>
        </tr>
    }

</table>

@Html.Partial("~/Views/Venta/modalCrear.cshtml")
@Html.Partial("~/Views/Cliente/modalCrear.cshtml")

<script>


        $(document).ready(function () {

            sendAjax(1);

            $("#tipopro").change(function () {
                let idana = $("#tipopro option:selected").val();
                console.log(idana);
                sendAjax(idana);
            });

            function sendAjax(idana) {
                let datasend = {
                    id: idana
                };

                $.ajax({
                    url: '@Url.Action("ComboProducto", "Venta")',
                    data: JSON.stringify(datasend),
                    type: 'POST',
                    dataType: 'json',
                    crossDomain: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        console.log("resultado: " + JSON.stringify(result.objeto[0].LABANALIS_Id));
                        console.log(result.objeto.length);
                        var le = result.objeto;
                        var ta = le.length;
                        $("#produc").empty();
                        for (i = 0; i < ta ; i++) {

                            $("#produc").append(`<option value='${result.objeto[i].idProducto}'>${result.objeto[i].nombre}</option>`);

                        }

                    },
                    error: function (error) {
                        alert('Error!' + JSON.stringify(error));
                    }
                });
            }




        });


</script>

InranetSystem/InranetSystem/Views/Venta/modalCrear.cshtml
<div class="modal fade" id="myModalCreate" role="dialog">
    <div class="modal-dialog modal-footer">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color:#f1f2f6">

                <h5 class="modal-title" id="exampleModalLabel">
                    REGISTRAR VENTA
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        &times;
                    </span>
                </button>
            </div>
            <div class="modal-body">
                <form id="frmModal">

                    <span class="m-accordion__item-title">
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                                DATOS CLIENTE
                            </font>
                        </font>
                    </span>
                    <br>
                    <br>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-6">
                            <label>
                                (*) Dni:
                            </label>
                            <div class="m-input-icon m-input-icon--left">
                                <div class="m-form m-form--state">
                                    <div class="form-group m-form__group" id="state-data-validate">
                                        <div class="m-typeahead">
                                            <input class="form-control m-input datasearch_number" id="datasearch" maxlength="8" type="text" placeholder="Ingrese DNI...">


                                        </div>
                                    </div>
                                </div>
                                <span class="m-input-icon__icon m-input-icon__icon--left">
                                    <span>
                                        <i class="la la-user"></i>
                                    </span>
                                </span>
                                <span class="m-input-icon__icon m-input-icon__icon--right" id="input_validate_data_true" style="visibility:hidden">
                                    <span>
                                        <i class="la la-check m--font-success"></i>
                                    </span>
                                </span>

                                <span class="m-input-icon__icon m-input-icon__icon--right" id="input_validate_data_false" style="visibility:hidden">
                                    <span>
                                        <i class="la la-close m--font-danger"></i>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label>
                                Apelidos y Nombres:
                            </label>
                            <div class="m-input-icon m-input-icon--left">
                                <div class="m-form m-form--state">
                                    <div class="form-group m-form__group" id="state-apeseg-validate">
                                        <input type="text" class="form-control m-input" placeholder="Ingrese Nombres" id="nompriE">
                                    </div>
                                </div>
                                <span class="m-input-icon__icon m-input-icon__icon--left">
                                    <span>
                                        <i class="la la-user"></i>
                                    </span>
                                </span>
                                <span class="m-input-icon__icon m-input-icon__icon--right" id="input_validate_nompriE_true" style="visibility:hidden">
                                    <span>
                                        <i class="la la-check m--font-success"></i>
                                    </span>
                                </span>

                                <span class="m-input-icon__icon m-input-icon__icon--right" id="input_validate_nompriE_false" style="visibility:hidden">
                                    <span>
                                        <i class="la la-close m--font-danger"></i>
                                    </span>
                                </span>
                            </div>

                            <div class="m-form m-form--state">
                                <div>
                                    <input type="text" class="form-control m-input" id="dvid" readonly disabled style="visibility:hidden">
                                </div>
                            </div>

                        </div>
                    </div>

                    <span class="m-accordion__item-title">
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">
                                DETALLE PRODUCTO
                            </font>
                        </font>
                    </span>
                    <br>
                    <br>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-5">
                            <label class="">
                                Tipo :
                            </label>
                            @Html.DropDownList("tipopro", (SelectList)ViewBag.TipoProducto, new { @style = "width:80%" })
                            <span class="m-form__help"></span>
                        </div>
                        <div class="col-lg-5">
                            <label>
                                Producto :
                            </label>
                            @Html.DropDownList("produc", (SelectList)ViewBag.Producto, new { @style = "width:80%" })
                            <span class="m-form__help"></span>
                        </div>
                        <br>
                        <br>
                        <br>
                        <button type="button" class="btn btn-success" id="btnAna" style='width:25px; height:30px'>+</button>
                        <br>
                        <br>
                        <br>
                        <div class="m-section">
                            <div class="m-section__content">
                                <br>
                                <br>

                                <table class="table m-table m-table--head-bg-success">
                                    <thead>
                                        <tr>
                                            <th>
                                                Tipo
                                            </th>
                                            <th>
                                                Producto
                                            </th>
                                            <th>
                                                Nombre
                                            </th>
                                            <th>
                                                Descripción
                                            </th>
                                            <th>
                                                Precio Venta
                                            </th>

                                            <th>
                                                Acciones
                                            </th>
                                        </tr>
                                    </thead>
                                </table>
                                <table class="table m-table m-table--head-bg-success" id="listDetalle"></table>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group m-form__group row">
                            <span class="m-form__help" style="font-size:12px">
                                &nbsp &nbsp   &nbsp   &nbsp &nbsp  &nbsp  &nbsp  &nbsp  Moneda : <b><span id="spMoneda">Soles</span></b>
                            </span>
                            <span class="m-form__help" style="font-size:12px">
                                &nbsp &nbsp   &nbsp   &nbsp &nbsp  &nbsp  &nbsp  &nbsp  Total : <b><span id="spStotal"></span></b>
                            </span>

                        </div>
                        <br>
                        <br>
                        <br>
                        <br>
                        <div>
                            <span class="m-accordion__item-title">
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">
                                        DETALLE VENTA
                                    </font>
                                </font>
                            </span>
                            <br>
                            <br>
                            <div class="form-group m-form__group row">

                                <div class="col-lg-6">
                                    <label class="">Cantidad :</label>

                                    <input type="text" class="form-control m-input" id="prcomcre">


                                    <span class="m-form__help"></span>
                                </div>
                                <div class="col-lg-6">
                                    <label class="">Precio :</label>

                                    <input type="text" class="form-control m-input" id="prvencre">


                                    <span class="m-form__help"></span>
                                </div>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
            <div class="modal-footer" style="background-color:#f1f2f6">
                <button type="button" class="btn btn-metal" data-dismiss="modal" id="btnCancelCreatePesona">
                    Cancelar
                </button>
                <button type="button" class="btn btn-success" id="btnSendCreate">
                    Registrar
                </button>
            </div>
        </div>
    </div>

</div>

<script>


    function mainjsfunction(inputFieldValue) {
        console.log(inputFieldValue);
        //do something with input field value
    }


                                    $('#datasearch').on('input', function () {
                                            if ($(this).val().trim() != '') {
                                                //Añado clases y muestro el span de error
                                                stateInput('data', 'false', 'true', 'danger', 'success');
                                            } else {
                                                stateInput('data', 'true', 'false', 'success', 'danger');
                                            }
                                    });


                                     $('#nompriE').on('input', function () {
                                                if ($(this).val().trim() != '') {
                                                    //Añado clases y muestro el span de error
                                                    stateInput('nom', 'false', 'true', 'danger', 'success');
                                                } else {
                                                    stateInput('nom', 'true', 'false', 'success', 'danger');
                                                }
                                     });

                                     let stateInput = (id, success, danger, hassucess, hasdanger) => {
                                            $(`#state-${id}-validate`).removeClass(`has-${hassucess}`);
                                            $(`#state-${id}-validate`).addClass(`has-${hasdanger}`);
                                            $(`#input_validate_${id}_${success}`).css(`visibility`, `hidden`);
                                            $(`#input_validate_${id}_${danger}`).css(`visibility`, `visible`);
                                  };
</script>